# Delete The Tweets

Your information is valuable - this much is a given. What most people do not think about, however,
is how we live in an age where your information can and *will* be used against you. Whether this is
an employer, employee, a fellow peer, an insurance company, your government, or some random anonymous
asshole, it is only a matter of time.

While it is Sisyphean task to eliminate your digital presence online, you can minimize it and make it harder at least
for those who want to use your information without your permission or in ways you never intended. This script is an
attempt in helping you in this endeavor.

## Small Preface

This script is targeted moreso at people with accounts who have excess of 3k tweets. I will shortly be releasing an additional
script to go with this repository that helps maintain your account below 3k tweets. If you are above 3k tweets, you will have to use the main script
first. If not, you can either use this script or wait till I release the simpler one.

## What You Need

0. Clone this repository
1. Python 3
2. Tweepy module
3. NLTK module
4. Your twitter API keys
5. Your twitter archive
6. Keywords and Likes Limit

## How to Get What You Need

### Cloning this repository

In terminal, cd into where you would like this project and simply perform the following:

#+BEGIN_SRC bash
git clone https://github.com/ejmg/delete-the-tweets.git
#+END_SRC

cd into the repository when ready to start the deletion.

### Python 3

I unfortunately will not cover how to install Python 3 for those who don't already have it. Luckily, there are plenty
of tutorials already online. If you are on some kind of Unix or Linux (that doesn't come pre-installed with Python 3),
I personally recommend [[https://github.com/yyuu/pyenv][Pyenv by yyuu.]] Another option that I hear works great (for both Windows and n*x systems) and that
requires next to 0% technical experience is [[https://docs.continuum.io/anaconda/install][Anaconda, a pre-packaged python management system.]]

### Tweepy and NLTK

Once you have Python3 (and PIP or Conda, see above), all you need to do is

#+BEGIN_SRC 
pip3 install tweepy nltk
#+END_SRC

Then, to properly install ~NLTK~, go to your terminal and enter python 3. Once you are in the interpreter, enter:

#+BEGIN_SRC python
import nltk
nltk.download("all")
#+END_SRC

Wait for this to finish and you will be ready to go.

### Twitter API Keys

I have written on this previously [[http://ageof.info/setting-up-twitter-bot-with-python-and-tweepy][here]], simply skip to the heading "Step 1."

For those who don't want to follow the tutorial, tl;dr: go to ~apps.twitter.com~, create an "app", and then go to
the tab ~keys and access tokens~. Create a file named ~secrets.py~ and save your keys in there as ~ACCESS_SECRET, ACCESS_TOKEN, CONSUMER_KEY~, and ~CONSUMER_SECRET~.
*I highly recommend you just look at my post for those who haven't done something like this before.*

### Your Twitter Archive

Logging on via desktop, click on your user image on the top right. You will see the option ~Settings and Privacy~, click on it.
Next, go to the bottom of the ~Account~ tab (this should be the one it sends you to by default) and request your twitter archive.
Twitter will send you the link for it via email. Save this archive somewhere safe and then extract its contents to the ~tweets~ subdirectory
of this repository. *Do not make another folder for it, it must be extracted as is to the ~tweets~ subdirectory*.

### Keywords and Likes Limit

A part of this script that others neglect is the ability to preserve tweets based on some kind of criteria. With this script, I define two simple
variables in ~options.py~ within the ~tweets~ subdirectory that help you have some control over this process. First, I let you create an list ~KEY_WORDS~ of keywords/user names that, 
if found in a tweet, will prevent the script from deleting it. Secondly, I have a simple constant ~LIKES~ that lets you preserve popular tweets of yours
if you want that. The names of these variables cannot change unless you change their identifiers from within the script. Your variables should look like so:

#+BEGIN_SRC python
KEY_WORDS = ["WORD", "USER_HANDLE_HERE", "BLAH"]
LIKES = 5
#+END_SRC

If you don't care for any keywords, simply leave the list empty. If you don't want to save any tweets with x number of likes, leave the variable with its default value of
None.

### You are now ready to go.

If you have done all the above as described, you can now execute the main script, with 

~python3 delete-the-tweets.py~

You will be prompted to confirm your actions as this *is a permanent process and cannot be undone*. You should be good to go from here. Beware, an account with a
 large amount of tweets will take some time to delete as Twitter's API limits requests on a fixed basis per 15 minutes. As a result, you will see the script declare
that it is ~sleeping!~ when this limit is hit. This will last 15 minutes and then continue unabated. This process will repeat as many times as necessary till done.
